config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'dashboard#index'
  mount API => '/'

  get 'pages/about', to: 'pages#about'
  scope '/admin' do
    resources :users
  end
  # 数据库操作路有命命方式: /dashboard/db_name/collection_name
  scope '/dashboard' do
    namespace :db_user do
      resources :user_configs
      resources :users
    end
    namespace :db_app do
      resources :app_infos
    end
  end
  scope '/test' do
    resources :tests
  end
end

app/controllers/db_app/app_infos_controller.rb
module DbApp
  class AppInfosController < ApplicationController
    def index
      @app_app_info_grid = AppAppInfoGrid.new(params[:app_app_info_grid]) do |scope|
        scope.page(params[:page]).per(25)
      end
    end

    def show
      @app_info = AppAppInfo.find(params[:id])
    end

    def edit
        @app_info = AppAppInfo.find(params[:id])
    end

    def destroy
      @app_info = AppAppInfo.find(params[:id]).delete
      redirect_to :back, notice: "Deleted." #dashboard_users_path
    end

    def create
      @app_info = AppAppInfo.create(app_info_params)
      redirect_to :back, notice: "Created." #dashboard_users_path
    end

    def update
      @app_info = AppAppInfo.find(params[:id])
      if @app_info.update(app_info_params)
        redirect_to :back, notice: "Updated." #dashboard_users_path
      end
    end

    def new
      @app_info = AppAppInfo.new
    end
    private
    def app_info_params
      reqParams = params.require(:app_app_info).permit(AppAppInfo.valid_attrs.keys)
      reqParams.each do |reqp|
        # logger.tagged("req params") { logger.debug reqParams}
        if AppAppInfo.fields[reqp[0]] && AppAppInfo.fields[reqp[0]].options[:type] == Array then
          reqParams[reqp[0]] = reqp[1].split(" ")
        end
        if AppAppInfo.fields[reqp[0]] && AppAppInfo.fields[reqp[0]].options[:type] == Hash then
          reqParams[reqp[0]] = JSON.parse(reqp[1])
        end
      end
      return reqParams
    end
  end
end

app/views/db_app/app_infos/_actions.html.erb
<div class="btn-group">
    <div class="btn-group">
        <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_db_app_app_info_path(obj.id), :class => "btn btn-xs btn-default", :'data-toggle' => "tooltip", :'data-original-title' => "Edit"%>

        <%= link_to '<i class="fa fa-times"></i>'.html_safe, db_app_app_info_path(obj.id), :method => :delete, :class => "btn btn-xs btn-default", :'data-toggle' => "tooltip", :'data-original-title' => "Remove", :'data-confirm' => "Confirm remove the item?"%>

        <%= link_to '<i class="fa fa-check-square-o"></i>'.html_safe, db_app_app_info_path(obj.id), :class => "btn btn-xs btn-default", :'data-toggle' => "tooltip", :'data-original-title' => "Show"%>
    </div>
</div>

app/views/db_app/app_infos/_form.html.erb
<% AppAppInfo.valid_attrs.each do |key, val| %>
  <% if (val == 'Hash') then%>
    <%= f.input key, as: :text, input_html: { class: 'simple-form-textArea', rows: 10 }%>
  <% else %>
    <%= f.input key%>
  <% end %>
<% end %>

<div class="form-group">
  <%= f.button :submit %>
</div>

app/views/db_app/app_infos/edit.html.erb
<% content_for(:page_header) do %>
  <%= "Database" %>
<% end %>
<% content_for :panel_heading do %>Edit App: app_info<% end %>
<div class="block">
  <div class="block-content">
    <%= simple_form_for @app_info, html: { class: 'form-horizontal' }, url: db_app_app_info_path(@app_info) do |f| %>
      <%= render :partial => 'form', :locals => {f: f} %>
    <% end %>
  </div>
</div>

app/views/db_app/app_infos/index.html.erb
<% content_for(:page_header) do %>
  <%= "Database" %>
<% end %>
<% content_for :panel_heading do %>App: app_info<% end %>
<% content_for :panel_button do %><a type="button" class="btn btn-primary" href=<%= new_db_app_app_info_path %>>create</a><% end %>
<%= datagrid_form_for @app_app_info_grid, :method => :get, :url => db_app_app_infos_path %>
<h4>Total: <span class="label label-primary"><%= @app_app_info_grid.assets.total_count %></span></h4>
<%= datagrid_table @app_app_info_grid %>
<%= paginate(@app_app_info_grid.assets) %>

app/views/db_app/app_infos/new.html.erb
<% content_for(:page_header) do %>
  <%= "Database" %>
<% end %>
<% content_for :panel_heading do %>Create App: app_info<% end %>

<div class="block">
  <div class="block-content">
    <%= simple_form_for @app_info, url: db_app_app_infos_path  do |f| %>
      <%= render :partial => 'form',:locals => {f: f} %>
    <% end %>
  </div>
</div>

app/views/db_app/app_infos/show.html.erb
<% content_for(:page_header) do %>
  <%= "Database" %>
<% end %>
<% content_for :panel_heading do %>Details App: app_info<% end %>

<h3>app_info</h3>
<div class="block">
  <div class="block-header">
    app_info #<%= @app_info.app_name %>
  </div>
  <div class="block-content">
    <div class="table-responsive">
      <table class="table table-striped table-bordered">
        <tbody>
          <% attrs = @app_info.attributes.except("_id").keys %>
          <% attrs.each do |a| %>
          <tr>
            <td><%= a.humanize %></td>
            <td><%= @app_info.attributes[a].to_s %></td>
          </tr>
          <% end %>

        </tbody>
      </table>
    </div>
  </div>
</div>