config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'dashboard#index'
  mount API => '/'

  get 'pages/about', to: 'pages#about'
  scope '/admin' do
    resources :users
  end
  # 数据库操作路有命命方式: /dashboard/db_name/collection_name
  scope '/dashboard' do
    namespace :db_user do
      resources :user_configs
      resources :users
    end
    namespace :db_app do
      resources :app_infos
    end
  end
  scope '/test' do
    resources :tests
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String
  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
  field :is_admin, type: Boolean, default: false
  field :name, type: String, default: ''

  def self.valid_attrs
    # res = attribute_names.delete_if{|i| i.in? ["_id","created_at","updated_at", ""]}
    res = ["name","email","is_admin"]
    res.map {|i| i.to_sym}
  end
end

app/controllers/db_user/users_controller.rb
module DbUser
  class UsersController < ApplicationController
    def index
    end
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users_grid = UsersGrid.new(params[:users_grid]) do |scope|
      scope.page(params[:page]).per(10)
    end
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

  def edit
      @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id]).delete
    redirect_to :back, notice: "Deleted." #dashboard_users_path
  end

  def create
    @user = User.create(user_params)
    redirect_to :back, notice: "Created." #dashboard_users_path
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to :back, notice: "Updated." #dashboard_users_path
    end      
  end

  def import
    User.import(params[:file])
    redirect_to :back, notice: "Imported."
  end
  def new
    @user = User.new
  end
  private
  def user_params
    params.require(:user).permit(User.valid_attrs)
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_actions.html.erb
<div class="btn-group">
    <div class="btn-group">
        <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_user_path(obj.id), :class => "btn btn-xs btn-default", :'data-toggle' => "tooltip", :'data-original-title' => "Edit"%>

        <%= link_to '<i class="fa fa-times"></i>'.html_safe, user_path(obj.id), :method => :delete, :class => "btn btn-xs btn-default", :'data-toggle' => "tooltip", :'data-original-title' => "Remove", :'data-confirm' => "Confirm remove the item?"%>

        <%= link_to '<i class="fa fa-search"></i>'.html_safe, user_path(obj.id), :class => "btn btn-xs btn-default", :'data-toggle' => "tooltip", :'data-original-title' => "Show"%>
    </div>
</div>

app/views/users/_form.html.erb
<% User.valid_attrs.each do |a| %>
  <%= f.input a %>
<% end %>

<div class="form-group">
  <%= f.button :submit %>
</div>

app/views/users/edit.html.erb
<% content_for(:page_header) do %>
  <%= "User" %>
<% end %>
<% content_for :panel_heading do %>Edit user<% end %>
<div class="block">
  <div class="block-content">
    <%= simple_form_for @user, html: { class: 'form-horizontal' }, url: user_path(@user) do |f| %>
      <%= render :partial => 'form', :locals => {f: f} %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% content_for(:page_header) do %>
  <%= "User" %>
<% end %>
<% content_for :panel_heading do %>User List<% end %>
<%= datagrid_form_for @users_grid, :method => :get, :url => users_path %>
<div class='total'>Total: <%= @users_grid.assets.total_count %></div>
<%= datagrid_table @users_grid %>
<%= paginate(@users_grid.assets) %>

app/views/users/new.html.erb
<% content_for(:page_header) do %>
  <%= "User" %>
<% end %>
<% content_for :panel_heading do %>Create user<% end %>

<div class="block">
  <div class="block-content">
    <%= simple_form_for @user, url: users_path  do |f| %>
      <%= render :partial => 'form',:locals => {f: f} %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% content_for(:page_header) do %>
  <%= "User profile" %>
<% end %>
<% content_for :panel_heading do %>Details<% end %>

<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>
<p>Is_Admin: <%= @user.is_admin if @user.is_admin %></p>