config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'dashboard#index'
  mount API => '/'

  get 'pages/about', to: 'pages#about'
  scope '/admin' do
    resources :users
  end
  # 数据库操作路有命命方式: /dashboard/db_name/collection_name
  scope '/dashboard' do
    namespace :db_user do
      resources :user_configs
      resources :users
    end
    namespace :db_app do
      resources :app_infos
    end
  end
  scope '/test' do
    resources :tests
  end
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
  <div class="navbar-header">
    <button class="navbar-toggle" data-target=".navbar-collapse" data-toggle="collapse" type="button">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">CMS Admin Panel</a>
  </div>

  <ul class="nav navbar-top-links navbar-right pull-right">
    <li class="dropdown">
      <a aria-expanded="false" class="dropdown-toggle" data-toggle="dropdown" href="#">
        <i class="fa fa-user fa-fw"></i>
        <i class="fa fa-caret-down"></i>
      </a>
      <ul class="dropdown-menu dropdown-user">
        <li>
          <%= link_to '<i class="fa fa-user fa-fw"></i>Profile</a>'.html_safe, user_path(current_user) %>
        </li>
        <li class="divider"></li>
        <li>
          <%= link_to '<i class="fa fa-sign-out fa-fw"></i>Logout</a>'.html_safe, destroy_user_session_path, :method=>'delete' %>
      </ul>
    </li>
  </ul>

  <div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
      <ul class="nav in" id="side-menu">
        <li>
          <a href="/">
            <i class="fa fa-dashboard fa-fw"></i>
            Dashboard</a>
        </li>
        <li>
          <a href="#"><i class="fa fa-database fa-fw"></i> Database<span class="fa arrow"></span></a>
          <ul class="nav nav-second-level collapse">
            <li>
              <a href="#">User<span class="fa arrow"></span></a>
              <ul class="nav nav-third-level">
                <li>
                    <a href="#">user</a>
                </li>
              </ul>
            </li>
            <li>
              <a href="#">App<span class="fa arrow"></span></a>
              <ul class="nav nav-third-level">
                <li>
                    <%= link_to 'app_info', db_app_app_infos_path %>
                </li>
              </ul>
            </li>
          </ul>
        </li>
        <li>
          <a href="#"><i class="fa fa-users fa-fw"></i> Users<span class="fa arrow"></span></a>
          <ul class="nav nav-second-level collapse">
            <li>
              <%= link_to 'User List', users_path %>
            </li>
          </ul>
        </li>
        <li>
          <a href=<%= tests_path %>>
            <i class="fa fa-smile-o fa-fw"></i>
            test</a>
        </li>
        <li>
          <a href="/pages/about">
            <i class="fa  fa-info-circle fa-fw"></i>
            About</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_title.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header"><%= content_for?(:page_header) ? yield(:page_header) : "Dashboard" %></h1>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    <%= content_for?(:title) ? yield(:title) : "CMS Admin Panel" %>
  </title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "CMS Admin Panel" %>">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div id="wrapper" class="">
    <%= render 'layouts/navbar' %>
  </div>

  <div id="page-wrapper">
    <%= render 'layouts/title' %>
    <%= render 'layouts/messages' %>

    <div>
      <div class="panel panel-default">
        <div class="panel-heading">
          <%= content_for?(:panel_heading) ? yield(:panel_heading) : "Dashboard" %>
          <p class="panel_button_heading">
            <%= content_for?(:panel_button) ? yield(:panel_button) : "" %>
          </p>
        </div>
        <div class="panel-body">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
</body>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= content_for?(:extra_scripts) ? yield(:extra_scripts) : nil %>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    <%= content_for?(:title) ? yield(:title) : "Sensors Admin Panel" %>
  </title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : " Sensors Admin Panel " %>">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-md-offset-4" style="text-align:center;">
        <h1>Tinfinite Server CMS</h1>
      </div>
    </div>

    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <div class="login-panel panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Please Sign In</h3>
          </div>
          <div class="panel-body">
            <%= yield %>
          </div>
          <% if (notice || alert) then %>
          <div class="panel-body">
            <div class="alert alert-success">
                <p class="notice"><%= notice %></p>
                <p class="alert"><%= alert %></p>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</body>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</html>